services:
  app:
    image: laravel-node  # Your custom Laravel image
    depends_on:
      - database  # Ensure the database service is up before the app starts
    volumes:
      - ./:/var/www/html:delegated
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache

    ports:
      - 8080:80  # Map host port 8080 to container port 80
    environment:
      - DB_CONNECTION=mysql  # Laravel database connection type
      - DB_HOST=database  # Database hostname (matches the service name)
      - DB_PORT=3306  # MySQL port
      - DB_DATABASE=laravel  # Database name
      - DB_USERNAME=ddn  # Database user
      - DB_PASSWORD=password  # Database password

  database:
    image: mysql:8.0.0  # MySQL image version 8.0.0
    environment:
      MYSQL_ROOT_PASSWORD: password  # Set root password for MySQL
      MYSQL_USER: ddn  # Custom MySQL user
      MYSQL_PASSWORD: password  # Password for custom user
      MYSQL_DATABASE: laravel  # Database name to create
    ports:
      - 8306:3306  # Map host port 8306 to container port 3306 (MySQL default)
    volumes:
      - database:/var/lib/mysql  # Persistent storage for the database

volumes:
  database:  # Define a named volume for MySQL data
